apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: income-expense-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
  - host: a69cc18f92aed481eaa852956a5ce70b-525573346.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: income-expense-service
            port:
              number: 80

